package com.july.backend.models;
// Generated Jun 10, 2018 5:38:52 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;


/**
 * Books generated by hbm2java
 */
@Entity
@Table(name = "books", catalog = "bookstore")
public class Books implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Category category;
	private String namebook;
	private String descbook;
	private Integer price;
	private String author;
	private String publish;

	public Books() {
	}

	public Books(Category category, String namebook, String descbook, Integer price, String author, String publish) {
		this.category = category;
		this.namebook = namebook;
		this.descbook = descbook;
		this.price = price;
		this.author = author;
		this.publish = publish;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "category_id")
	@JsonManagedReference
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "namebook")
	public String getNamebook() {
		return this.namebook;
	}

	public void setNamebook(String namebook) {
		this.namebook = namebook;
	}

	@Column(name = "descbook", length = 1000)
	public String getDescbook() {
		return this.descbook;
	}

	public void setDescbook(String descbook) {
		this.descbook = descbook;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "author")
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "publish")
	public String getPublish() {
		return this.publish;
	}

	public void setPublish(String publish) {
		this.publish = publish;
	}

}
